using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace Onemore.Protobuf.CodeGenerate
{
    /// <summary>
    /// just code it for fun, can use Google.Protoc compile the auto genetated proto file
    /// </summary>
    public static class GenCSharp
    {
        public static string GenCode(MessageManager manager, string file = null)
        {
            _buffer.Length = 0;
            GenMessageManager(manager);
            var content = _buffer.ToString();
            if (string.IsNullOrEmpty(file) == false)
            {
                File.WriteAllText(file, content, _utf8);
            }
            return content;
        }


        static Encoding _utf8 = new UTF8Encoding(true, true);// utf-8 with bom
        static StringBuilder _buffer = new StringBuilder();
        private static void AppendFormat(string format, params object[] args)
        {
            if (args.Length > 0)
            {
                _buffer.AppendFormat(format, args);
            }
            else
            {
                _buffer.Append(format);
            }

        }
        private static void Append(int indent, string format, params object[] args)
        {
            _buffer.Append(' ', indent * 4);
            if (args.Length > 0) // WTF
            {
                _buffer.AppendFormat(format, args);
            }
            else
            {
                _buffer.Append(format);
            }
        }
        private static void AppendLine(int indent, string format, params object[] args)
        {
            Append(indent, format, args);
            AppendLine();
        }
        private static void AppendLine()
        {
            _buffer.AppendLine();
        }

        static void GenMessageManager(MessageManager manager)
        {
            AppendLine(0, @"// This Code was generated by Onemore.Protobuf. Do not edit it!");
            AppendLine();
            AppendLine(0, @"using System.Collections.Generic;");
            AppendLine();
            AppendLine(0, @"using InputStream = Onemore.Protobuf.InputStream;");
            AppendLine(0, @"using OutputStream = Onemore.Protobuf.OutputStream;");
            AppendLine(0, @"using WireFormat = Onemore.Protobuf.WireFormat;");
            AppendLine(0, @"using WireType = Onemore.Protobuf.WireFormat.WireType;");
            AppendLine(0, @"using IMessage = Onemore.Protobuf.IMessage;");
            AppendLine();
            AppendLine(0, "namespace {0} {{", manager.m_namespace);
            foreach (var penum in manager.m_enums.Values)
            {
                GenEnum(penum);
                AppendLine();
            }
            foreach (var message in manager.m_messages.Values)
            {
                GenMessage(message);
                AppendLine();
            }
            AppendLine(0, "}");
        }

        static void GenEnum(PEnum penum)
        {
            AppendLine(1, "public enum {0}", penum.m_name);
            AppendLine(1, "{");
            foreach (var item in penum.m_items.OrderBy(item_ => item_.Value))
            {
                AppendLine(2, "{0} = {1},", item.Key, item.Value);
            }
            AppendLine(1, "}");
        }

        static void GenMessage(MessageInfo message)
        {
            AppendLine(1, "public sealed class {0} : IMessage", message.m_name);
            AppendLine(1, "{");
            PreGenField(message);
            foreach (var field in cur_gen_fields)
            {
                DefineField(field);
                AppendLine();
            }
            GenMessageWriteTo(message);
            AppendLine();
            GenMessageReadFrom(message);
            AppendLine();
            GenMessageGetSize(message);
            AppendLine();
            GenMessageCalculateSize(message);
            AppendLine(1, "}");
        }

        class FieldInfoForGen
        {
            public string name_get;
            public string name_get_has_set;

            public string name_define;
            public string name_has_set;
            public string name_size;
            public string name_packed_size;
            public string name_type;
            public string name_type_item;// for array

            public FieldInfo field_info;

            public void GenWriteCode(int indent, string write_name = null)
            {
                if (write_name == null) write_name = name_define;
                switch(field_info.m_type)
                {
                    case FieldFormat.FieldType.InValid:
                        throw new NotSupportedException();
                    case FieldFormat.FieldType.Message:
                        AppendLine(indent, "_output.WriteLength({0}.GetSize());", write_name);
                        AppendLine(indent, "{0}.WriteTo(_output);", write_name);
                        break;
                    case FieldFormat.FieldType.Enum:
                        AppendLine(indent, "_output.WriteEnum((int){0});", write_name);
                        break;
                    default:
                        AppendLine(indent, "_output.Write{1}({0});", write_name, Enum.GetName(typeof(FieldFormat.FieldType), field_info.m_type));
                        break;
                }
            }

            public void GenReadCode(int indent, string read_name = null)
            {
                bool need_new = read_name != null;
                if (read_name == null) read_name = name_get;
                switch (field_info.m_type)
                {
                    case FieldFormat.FieldType.InValid:
                        throw new NotSupportedException();
                    case FieldFormat.FieldType.Message:
                        if(need_new)
                        {
                            AppendLine(indent, "var {0} = new {1}();", read_name, name_type_item);
                        }
                        // todo only for dragonnest
                        else
                        {
                            AppendLine(indent, "{0} = new {1}();", name_define, name_type_item);
                        }
                        AppendLine(indent, "{0}.InternalReadFrom(_input);", read_name);
                        break;
                    case FieldFormat.FieldType.Enum:
                        if (need_new)
                        {
                            AppendLine(indent, "var {0} = ({1})_input.ReadEnum();", read_name, name_type_item);
                        }
                        else
                        {
                            AppendLine(indent, "{0} = ({1})_input.ReadEnum();", read_name, name_type_item);
                        }
                        break;
                    default:
                        if(need_new)
                        {
                            AppendLine(indent, "var {0} = _input.Read{1}();", read_name, Enum.GetName(typeof(FieldFormat.FieldType), field_info.m_type));
                        }
                        else
                        {
                            AppendLine(indent, "{0} = _input.Read{1}();", read_name, Enum.GetName(typeof(FieldFormat.FieldType), field_info.m_type));
                        }
                        break;
                }
            }

            public void GenCalculateCodeSnippet(string var_name)
            {
                switch (field_info.m_type)
                {
                    case FieldFormat.FieldType.InValid:
                        throw new NotSupportedException();
                    case FieldFormat.FieldType.Message:
                        AppendFormat("{0}.CalculateSize() + OutputStream.ComputeLengthSize({0}.GetSize());", var_name);
                        break;
                    case FieldFormat.FieldType.Enum:
                        AppendFormat("OutputStream.ComputeEnumSize((int){0});", var_name);
                        break;
                    default:
                        AppendFormat("OutputStream.Compute{0}Size({1});",
                            Enum.GetName(typeof(FieldFormat.FieldType), field_info.m_type),
                            var_name);
                        break;
                }
            }
        }
        static List<FieldInfoForGen> cur_gen_fields = new List<FieldInfoForGen>();

        static void PreGenField(MessageInfo message)
        {
            cur_gen_fields.Clear();
            foreach (var field in message.m_fields.Values.OrderBy(_ => _.m_index))
            {
                FieldInfoForGen gen_field = new FieldInfoForGen();
                gen_field.field_info = field;
                gen_field.name_get = field.m_name;
                gen_field.name_get_has_set = field.m_name + "Specified";

                gen_field.name_define = "__" + gen_field.name_get;
                gen_field.name_has_set = "__" + gen_field.name_get_has_set;
                gen_field.name_packed_size = "__" + gen_field.name_get + "__packed_size";
                gen_field.name_type_item = GetFieldTypeName(field);
                if (field.m_is_array)
                {
                    gen_field.name_type = string.Format("List<{0}>", gen_field.name_type_item);
                }
                else
                {
                    gen_field.name_type = gen_field.name_type_item;
                }
                cur_gen_fields.Add(gen_field);
            }
        }

        static void DefineField(FieldInfoForGen gen_field)
        {
            FieldInfo field = gen_field.field_info;
            // Get and set
            {
	            AppendLine(2, "public {0} {1}", gen_field.name_type, gen_field.name_get);
	            AppendLine(2, "{");
	            //if(field.m_type == FieldFormat.FieldType.Message || field.m_is_array)
	            //{
	            //    AppendLine(3, "get {");
	            //    {
	            //        AppendLine(4, "if ({0} == false) {{", gen_field.name_has_set);
	            //        {
		           //         AppendLine(5, "{0} = true;", gen_field.name_has_set);
		           //         AppendLine(5, "{0} = new {1}();", gen_field.name_define, gen_field.name_type);
	            //        }
	            //        AppendLine(4, "}");
	            //    }
	            //    {
	            //        AppendLine(4, "return {0};", gen_field.name_define);
	            //    }
	            //    AppendLine(3, "}");
	            //}
	            //else
	            //{
	            //    AppendLine(3, "get {{ {0} = true; return {1}; }}", gen_field.name_has_set, gen_field.name_define);
	            //    AppendLine(3, "set {{ {0} = true; {1} = value; }}",gen_field.name_has_set, gen_field.name_define);
	            //}
                
                // for dragonnest game
                if (field.m_is_array)
                {
                    AppendLine(3, "get {");
                    {
                        AppendLine(4, "if ({0} == false) {{", gen_field.name_has_set);
                        {
                            AppendLine(5, "{0} = true;", gen_field.name_has_set);
                            AppendLine(5, "{0} = new {1}();", gen_field.name_define, gen_field.name_type);
                        }
                        AppendLine(4, "}");
                    }
                    {
                        AppendLine(4, "return {0};", gen_field.name_define);
                    }
                    AppendLine(3, "}");
                }
                else
                {
                    AppendLine(3, "get {{ return {0}; }}", gen_field.name_define);
                    AppendLine(3, "set {{ {0} = true; {1} = value; }}", gen_field.name_has_set, gen_field.name_define);
                }
                AppendLine(2, "}");
            }
            // Other
            {
                AppendLine(2, "public bool {0} {{ get{{ return {1}; }} set{{ {1} = value; }} }}", gen_field.name_get_has_set, gen_field.name_has_set);
                AppendLine(2, "private {0} {1};", gen_field.name_type, gen_field.name_define);
                AppendLine(2, "private bool {0};", gen_field.name_has_set);
                if(field.m_is_packed)
                {
                    AppendLine(2, "private int {0};", gen_field.name_packed_size);
                }
            }
        }

        static void GenMessageWriteTo(MessageInfo message)
        {
            AppendLine(2, "public void WriteTo(OutputStream _output)");
            AppendLine(2, "{");
            {
                AppendLine(3, "if (_size == 0) CalculateSize();");
                foreach (var gen_field in cur_gen_fields)
                {
                    var field = gen_field.field_info;
                    AppendLine(3, "if ({0}) {{", gen_field.name_has_set);
                    if(field.m_is_array)
                    {
                        if(field.m_is_packed)
                        {
                            AppendLine(4, "_output.WriteTag({0});", field.m_tag);
                            AppendLine(4, "_output.WriteLength({0});", gen_field.name_packed_size);
                            AppendLine(4, "foreach (var _item in {0}) {{", gen_field.name_define);
                            gen_field.GenWriteCode(5, "_item");
                            AppendLine(4, "}");
                        }
                        else
                        {
                            AppendLine(4, "foreach (var _item in {0}) {{", gen_field.name_define);
                            AppendLine(5, "_output.WriteTag({0});", field.m_tag);
                            gen_field.GenWriteCode(5, "_item");
                            AppendLine(4, "}");
                        }
                    }
                    else
                    {
                        AppendLine(4, "_output.WriteTag({0});", field.m_tag);
                        gen_field.GenWriteCode(4);
                    }
                    AppendLine(3, "}");
                }
            }
            AppendLine(2, "}");
        }

        static void GenMessageReadFrom(MessageInfo message)
        {
            AppendLine(2, "public void ReadFrom(InputStream _input)");
            AppendLine(2, "{");
            {
                AppendLine(3, "uint _tag;");
                AppendLine(3, "while ((_tag = _input.ReadTag()) != 0) { ReadOneField(_input, _tag); }");
            }
            AppendLine(2, "}");

            AppendLine(2, "internal void InternalReadFrom(InputStream _input)");
            AppendLine(2, "{");
            {
                AppendLine(3, "var _message_len = _input.ReadLength();");
                AppendLine(3, "var _end_pos = _input.Position + _message_len;");
                AppendLine(3, "while(_input.Position < _end_pos) {");
                {
	                AppendLine(4, "uint _tag = _input.ReadTag();");
	                AppendLine(4, "ReadOneField(_input, _tag);");
                }
                AppendLine(3, "}");
            }
            AppendLine(2, "}");

            AppendLine(2, "private void ReadOneField(InputStream _input, uint _tag)");
            AppendLine(2, "{");
            {
                AppendLine(3, "WireType _wire_type = WireFormat.GetTagWireType(_tag);");
                AppendLine(3, "int _index = WireFormat.GetTagFieldNumber(_tag);");
                AppendLine(3, "switch (_index) {");
                foreach (var gen_field in cur_gen_fields)
                {
                    var field = gen_field.field_info;
                    AppendLine(4, "case {0}:", field.m_index);
                    if (field.m_is_array)
                    {
                        if (field.m_is_packed)
                        {
                            AppendLine(5, "if (_wire_type == WireType.LengthDelimited) {");
                            {
                                AppendLine(6, "int _len = _input.ReadLength();");
                                AppendLine(6, "var _end_pos_arr = _input.Position + _len;");
                                AppendLine(6, "while(_input.Position < _end_pos_arr) {");
                                {
                                    gen_field.GenReadCode(8, "_item");
                                    AppendLine(7, "{0}.Add(_item);", gen_field.name_get);
                                }
                                AppendLine(6, "}");
                            }
                            AppendLine(5, "}");
                            AppendLine(5, "else { ");
                            {
                                gen_field.GenReadCode(6, "_item");
                                AppendLine(6, "{0}.Add(_item);", gen_field.name_get);
                            }
                            AppendLine(5, "}");
                        }
                        else
                        {
                            AppendLine(5, "{");
                            {
                                gen_field.GenReadCode(6, "_item");
                                AppendLine(6, "{0}.Add(_item);", gen_field.name_get);
                            }
                            AppendLine(5, "}");
                        }
                        AppendLine(5, "break;");
                    }
                    else
                    {
                        gen_field.GenReadCode(5);
                        AppendLine(5, "break;");
                    }
                }
                {
                    AppendLine(4, "default:");
                    AppendLine(5, "_input.SkipField(_wire_type);");
                    AppendLine(5, "break;");
                }
                AppendLine(3, "}");
            }
            AppendLine(2, "}");
        }

        static void GenMessageCalculateSize(MessageInfo message)
        {
            AppendLine(2, "public int CalculateSize()");
            AppendLine(2, "{");
            {
                AppendLine(3, "_size = 0;");
                foreach (var gen_field in cur_gen_fields)
                {
                    var field = gen_field.field_info;
                    AppendLine(3, "if ({0}) {{", gen_field.name_has_set);
                    int tag_size = OutputStream.ComputeTagSize(field.m_tag);
                    if (field.m_is_array)
                    {
                        AppendLine(4, "int _arr_size = 0;");
                        if (field.m_is_packed)
                        {
                            AppendLine(4, "{0} = 0;", gen_field.name_packed_size);
                            AppendLine(4, "foreach (var _item in {0}) {{", gen_field.name_define);
                            {
                                Append(5, "{0} += ", gen_field.name_packed_size);
                                gen_field.GenCalculateCodeSnippet("_item");
                                AppendLine();
                            }
                            AppendLine(4, "}");
                            AppendLine(4, "_arr_size = {0} + {1} + OutputStream.ComputeLengthSize({1});", tag_size, gen_field.name_packed_size);
                        }
                        else
                        {
                            AppendLine(4, "foreach (var _item in {0}) {{", gen_field.name_define);
                            {
                                Append(5, "_arr_size += {0} + ", tag_size);
                                gen_field.GenCalculateCodeSnippet("_item");
                                AppendLine();
                            }
                            AppendLine(4, "}");
                        }
                        AppendLine(4, "_size += _arr_size;");
                    }
                    else
                    {
                        Append(4, "_size += {0} + ", tag_size);
                        gen_field.GenCalculateCodeSnippet(gen_field.name_define);
                        AppendLine();
                    }
                    AppendLine(3, "}");
                }
                AppendLine(3, "return _size;");
            }
            AppendLine(2, "}");
        }

        static void GenMessageGetSize(MessageInfo message)
        {
            AppendLine(2, "private int _size = 0;");
            AppendLine(2, "public int GetSize() { return _size; }");
        }

        static string GetFieldTypeName(FieldInfo field_info)
        {
            var field_type = field_info.m_type;
            switch (field_type)
            {
                case FieldFormat.FieldType.InValid:
                    throw new NotSupportedException();
                case FieldFormat.FieldType.Int32:
                    return "int";
                case FieldFormat.FieldType.UInt32:
                    return "uint";
                case FieldFormat.FieldType.Int64:
                    return "long";
                case FieldFormat.FieldType.UInt64:
                    return "ulong";
                case FieldFormat.FieldType.Bool:
                    return "bool";
                case FieldFormat.FieldType.Enum:
                    return field_info.m_type_name;
                case FieldFormat.FieldType.SInt32:
                    return "int";
                case FieldFormat.FieldType.SInt64:
                    return "long";
                case FieldFormat.FieldType.String:
                    return "string";
                case FieldFormat.FieldType.Bytes:
                    return "byte[]";
                case FieldFormat.FieldType.Message:
                    return field_info.m_type_name;
                case FieldFormat.FieldType.Fixed64:
                    return "fixed64";
                case FieldFormat.FieldType.SFixed64:
                    return "sfixed64";
                case FieldFormat.FieldType.Double:
                    return "double";
                case FieldFormat.FieldType.Fixed32:
                    return "fixed32";
                case FieldFormat.FieldType.SFixed32:
                    return "sfixed32";
                case FieldFormat.FieldType.Float:
                    return "float";
                default:
                    throw new Exception();
            }
        }
    }
}
